import type { Metadata } from "next";
import { Syne_Mono, Zen_Dots } from "next/font/google";
import "./globals.css";

const zenDots = Zen_Dots({
  variable: "--font-zen-dots",
  subsets: ["latin"],
  weight: ["400"],
});

const syneMono = Syne_Mono({
  variable: "--font-syne-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zenDots.variable} ${syneMono.variable} antialiased flex flex-col items-center justify-center max-w-6xl mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
